---
- hosts: wordpress
  tasks:
    - name: 'Instala pacotes do sistema operacional'
      apt:
        name:
        - php
        - apache2
        - libapache2-mod-php
        - php-ssh2
        - python3-mysqldb
        - mariadb-server
        - mariadb-client
        state: latest
      become: yes

    - name: 'Cria o banco do MySQL'
      mysql_db: 
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Cria o usuário do MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes

# Descomente a task abaixo caso irá executar o download do wordpress a primeira vez

#    - name: 'Baixa o arquivo de instalacao do Wordpress'
#      get_url: 
#        url: 'https://wordpress.org/latest.tar.gz'
#        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descomparta o Wordpress'
      unarchive: 
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www'
        remote_src: yes
      become: yes

    - name: 'Adiciona arquivo wp-config.php'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config'
      replace: 
        path: '/var/www/wordpress/wp-config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value}}'
      with_items:
          - { regex: 'database_name_here', value: 'wordpress_db'}
          - { regex: 'username_here', value: 'wordpress_user'}
          - { regex: 'password_here', value: '12345'}
      become: yes